version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:openjdk-11

    environment:
      TEST_REPORTS: /tmp/test-reports

    working_directory: ~/Magnum-Opus/Project/Project1

    steps:
      - run: cd ~/Magnum-Opus/Project/Project1

      - checkout:

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-{{ checksum "pom.xml" }}

        # run tests!
      - run: mvn verify

      # Save artifacts
      - store_artifacts:
          path: /tmp/artifacts
          destination: build

      # Upload test results
      - store_test_results:
          path: /tmp/test-reports

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - develop
                - /feature-.*/
