version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:openjdk-11
    working_directory: ~/Magnum Opus/Project/Project1
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout:
          path: ~/Project1

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: spring-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn verify