version: 2.1

commands:
  restore_cache_cmd:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-
  save_cache_cmd:
    steps:
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
  test:
    steps:
      - checkout
      - restore_cache_cmd
      - run: mvn test
      - save_cache_cmd


executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:openjdk-11


jobs:
  test-with-docker:
    executor: docker-executor
    working_directory: ~/Magnum-Opus/Project/Project1
    steps:
      - test


workflows:
  app-test-with-docker:
    jobs:
      - test-with-docker