apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.app.istio.gateway.configName }}
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: {{ .Values.app.istio.gateway.portNumber }}
      name: http
      protocol: HTTP
    hosts:
    - "*"   # Domain name of the external website
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: spring-webapp
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.app.istio.gateway.configName }}
  http:
    - match:
      - uri: 
          prefix: {{ .Values.app.istio.gateway.urlPrefix }}
      rewrite:
        uri: "/"
      route:
      - destination:
          host: {{ .Values.app.service.name }}
          subset: stable
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.app.istio.dr.name }}
spec:
  host: {{ .Values.app.service.name }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http2MaxRequests: 1000
        maxRequestsPerConnection: 50
  subsets:
    - labels:
        version: stable
      name: stable
    - labels:
        version: experimental
      name: experimental