apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }}
spec:
  type: {{ .Values.app.service.type }}
  selector:             
    app: {{ .Values.app.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}       
      targetPort: {{ .Values.app.container.port }}