jenkins:
  systemMessage: "Jenkins Configured using Code"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  

  securityRealm:
    local:
      allowsSignup: false
      users:
       - id: admin
         password: ${adminpw:-passw0rd}

  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Read:anonymous"
        - "Job/Read:anonymous"
        - "View/Read:anonymous"
        - "Overall/Administer:anonymous"

  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true    

unclassified:
  location:
    adminAddress: "istiyaksiddiquee@gmail.com"    

  # Configure SonarQube plugin
  sonarglobalconfiguration:
    installations:
      - name: SonarQube
        serverUrl: ${SONARQUBE_URL}
        serverAuthenticationToken: ${SONARQUBE_TOKEN}

tool:
  git:
    installations:
      - name: Default
        home: "git"
  jdk:
    installations:
      - name: "open-jdk8"
        home: "/usr/lib/jvm/java-11-openjdk-amd64"
  maven:
    installations:
      - name: "Maven 3"
        properties:
          - installSource:
              installers:
                - maven:
                    id: "3.6.3"
  sonarRunnerInstallation:
    installations:
    - name: "sonar-scanner-default"
      home: ""
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.2.0.1873" 