jobs:
  - script: >
        pipelineJob('${PIPELINE_ID}') {
            configure { project ->
                (project / 'authToken').setValue('${AUTOMATED_BUILD_TOKEN}')
            }
            definition {
                cpsScm {
                    scm {
                        git {
                            remote { 
                                url("file://${PROJECT_HOME}")
                            }
                            branch '*/master'
                            extensions {}
                        }
                    }
                scriptPath 'Jenkinsfile'
                }
            }
        }