jobs:
  - script: >
      pipelineJob('maven-pipeline-version-controlled') {
          definition {
              quietPeriod(120)
              cpsScm {
                  scm {
                    git {
                        remote { 
                            url("file://${PROJECT_HOME}")
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
                  scriptPath 'Jenkinsfile'
              }
          }
      }