version: '3.8'

services:
  jenkins:
    hostname: jenkins
    container_name: jenkins_compose 
    build: 
      context: ./JenkinsBuilder/master/
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./JenkinsBuilder/config:/var/jenkins_conf
      - /var/run/docker.sock:/var/run/docker.sock
      - C:\Users\Istiyak\.kube:/root/.kube
      - E:\Codes\Magnum Opus:/home/project
    secrets:
      - source: admin_password
        target: ADMIN_PASSWORD
      - source: automated_build_token
        target: AUTOMATED_BUILD_TOKEN
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_conf    
      - PROJECT_HOME=/home/project
      - PIPELINE_ID=automated_build      

    # depends_on:
    #   - "sonarqube"
    # networks:
    #   - sonarnet

  # sonarqube:
  #   image: sonarqube:latest
  #   volumes:
  #     - sonarqube_conf:/opt/sonarqube/conf
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  #   ports:
  #     - '9000:9000'
  #   depends_on:
  #     - "sonardb"
  #   networks:
  #     - sonarnet
  #   environment:
  #     - sonar.jdbc.username=sonar
  #     - sonar.jdbc.password=sonar
  #     - sonar.jdbc.url=jdbc:postgresql://sonardb:5432/sonar
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'
  #         memory: 500M

  # sonardb:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   networks:
  #     - sonarnet
  #   volumes:
  #     - sonar_postgresql:/var/lib/postgresql
  #     - sonar_postgresql_data:/var/lib/postgresql/data

volumes:
  # sonarqube_conf:
  # sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_bundled-plugins:
  # sonar_postgresql:
  # sonar_postgresql_data:
  jenkins_home:

secrets:
  admin_password:
    file: "${WORKDIR-.}/secrets/admin_password"
  sonarqube_token:
    file: "${WORKDIR-.}/secrets/sonarqube_token"
  automated_build_token: 
    file: "${WORKDIR-.}/secrets/automated_build_token"

# networks:
#   sonarnet:
#     driver: bridge