version: 2.1

commands:
  test:
    steps:
      - checkout      
      - run: cd ./Project/Project1 && mvn test      

executors:
  docker-executor:
    docker:
      - image: circleci/openjdk:15-buster-node


jobs:
  test-with-docker:
    executor: docker-executor
    working_directory: ~/Magnum-Opus
    steps:
      - test


workflows:
  app-test-with-docker:
    jobs:
      - test-with-docker