apiVersion: v1
name: Alexandria
version: 0.1.0
appVersion: 1.16.0
maintainers:
  - name: Istiyak Siddiquee
    email: mohammad.siddiquee@st.ovgu.de
description: Alexandria is a microservice, written in go, for maintaining day to day activities of a university library
keywords:
  - Kubernetes
  - library
home: istiyaksiddiquee.github.io