go:
  name: alexandria
  version: stable
  spec: 
    replicaCount: 3
    revisionHistoryLimit: 3
    updateStrategy:
      maxUnavailable: 1
      maxSurge: 50%
  container:
    image: istiyaksiddiquee/alexandria
    tag: BUILD_NO
    port: ALEXANDRIA_PORT
    env:
      - key: dummy
        value: "dummy_value"
    resources:
      requests: 
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "500m"    
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: 
      initialDelaySeconds: 15
      periodSeconds: 20
    hpa:
      minReplicas: 1
      maxReplicas: 10
  service:
    name: alexandria-svc
    type: ClusterIP
    port: 31009
  ingress:
    name: alexandria-ing    
    host: localhost
    path: /
    servicePort: 31009
  istio:
    gateway:
      configName: ingress-gateway-configuration
      portNumber: 80
      urlPrefix: prefix_here
    dr:
      name: go-webapp
      hostName: go-webapp