nest:
  name: noticemgmt
  version: stable
  spec: 
    replicaCount: 3
    revisionHistoryLimit: 3
    updateStrategy:
      maxUnavailable: 1
      maxSurge: 50%
  container:
    image: istiyaksiddiquee/noticemanagement
    tag: BUILD_NO
    port: 4000
    env: 
      - key: dummy
        value: "value"
    resources:
      requests: 
        memory: "512Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "500m"    
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: 
      initialDelaySeconds: 15
      periodSeconds: 20
    hpa:
      minReplicas: 1
      maxReplicas: 10
  service:
    name: noticemanagement-svc
    type: ClusterIP
    port: 31008
  ingress:
    name: noticemanagement-ing    
    host: localhost
    path: /
    servicePort: 31008
  istio:
    gateway:
      configName: ingress-gateway-configuration
      portNumber: 80
      urlPrefix: prefix_here
    dr:
      name: nest-webapp
      hostName: nest-webapp