db:
  host: 'localhost'
  username: 'magnumopus'
  password: '123456'
  synchronize: true
  
test:
  info: 'dev'

mongo:
  host: 'localhost'
  username: 'magnumopus'
  password: '123456'
  synchronize: true