apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.go.service.name }}
spec:
  type: {{ .Values.go.service.type }}
  selector:             
    app: {{ .Values.go.name }}
  ports:
    - name: http-web
      port: {{ .Values.go.service.port }}
      targetPort: {{ .Values.go.container.port }}