version: '3.8'

services:
  postgres_db:
    hostname: postgres
    container_name: magnum_pgdb
    image: postgres:13
    ports: 
      - 5432:5432
    volumes:
      - pg-datastore:/var/lib/postgresql
      - ./dev-PostgresDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    # secrets:
    #   - source: db_password
    #     target: DB_PASSWORD
    environment: 
      - POSTGRES_PASSWORD=password
    networks:
      - backend
  pgadmin:
    hostname: pgadmin
    container_name: magnum_pgadmin
    image: dpage/pgadmin4:latest
    ports: 
      - 5050:80 
    environment:
      - PGADMIN_DEFAULT_EMAIL=istiyak@google.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    depends_on: 
      - postgres_db
    networks:
      - backend
    
  
  # user_mgmt:
  #   container_name: user_management
  #   build:
  #     context: ./Project1
  #     dockerfile: Dockerfile
  #   ports: 
  #     - 8080:8080
  #   networks:
  #     - backend
  #   depends_on:
  #     - postgres_db


volumes:
  pg-datastore:

# secrets:
#   db_password:
#     file: "./PostgresDB/db_password"  

networks:
  backend:
    driver: bridge    