releases:

  - name: pgdb
    namespace: development
    wait: true
    chart: ./charts/postgresql
    values:
      - ./charts/postgresql/values.yaml

  - name: spring-usermanagement
    namespace: development
    chart: ./charts/spring-usermanagement
    values:
      - ./values/spring-usermanagement-values.yaml
    needs:
      - development/pgdb