app:
  name: emoji-svc
  spec: 
    replicaCount: 1
    revisionHistoryLimit: 3
    updateStrategy:
      maxUnavailable: 1
      maxSurge: 50%    
  container:
    image: buoyantio/emojivoto-emoji-svc:v10
    port: 8080
    env: 
      - key: GRPC_PORT
        value: "8080"
    resources:
      requests: 
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "500m"
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe: 
      initialDelaySeconds: 15
      periodSeconds: 20
  service:
    type: ClusterIP
    port: 31008