apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/host_mnt/e/Codes/pv_mount_for_magnumpgdb"