apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ms-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

--- 

# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ms-slave-pv-claim
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi