# apiVersion: networking.istio.io/v1alpha3
# kind: Gateway
# metadata:
#   name: {{ .Values.app.istio.gateway.configName }}
# spec:
#   selector:
#     istio: ingressgateway # use Istio default gateway implementation
#   servers:
#   - port:
#       number: {{ .Values.app.istio.gateway.portNumber }}
#       name: http
#       protocol: HTTP
#     hosts:
#     - "*"   # Domain name of the external website
# ---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: nest-webapp
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.nest.istio.gateway.configName }}
  http:
    - name: "nest-v1-routes"
      match:
      - uri: 
          prefix: {{ .Values.nest.istio.gateway.urlPrefix }}
      rewrite:
        uri: "/"
      route:
      - destination:
          host: {{ .Values.nest.service.name }}
          subset: stable
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: {{ .Values.nest.istio.dr.name }}
spec:
  host: {{ .Values.nest.service.name }}
  subsets:
    - labels:
        version: stable
      name: stable
    - labels:
        version: experimental
      name: experimental