apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nest.service.name }}
spec:
  type: {{ .Values.nest.service.type }}
  selector:             
    app: {{ .Values.nest.name }}
  ports:
    - name: http-web
      port: {{ .Values.nest.service.port }}
      targetPort: {{ .Values.nest.container.port }}