apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.log.elastic.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.elastic.label }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.log.elastic.name }}
  labels:
    k8s-app: {{ .Values.log.elastic.label }}
rules:
- apiGroups:
  - ""
  resources:
  - "services"
  - "namespaces"
  - "endpoints"
  verbs:
  - "get"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kube-system
  name: {{ .Values.log.elastic.name }}
  labels:
    k8s-app: {{ .Values.log.elastic.label }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.log.elastic.name }}
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ .Values.log.elastic.name }}
  apiGroup: ""
