apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.log.elastic.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.elastic.label }}
spec:
  serviceName: {{ .Values.log.elastic.name }}
  replicas: 2
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: {{ .Values.log.elastic.label }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.log.elastic.label }}
    spec:
      serviceAccountName: {{ .Values.log.elastic.name }}
      containers:
      - image: elasticsearch:6.8.4
        name: {{ .Values.log.elastic.name }}
        ports:
        - containerPort: 9200
          name: db
          protocol: TCP
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: {{ .Values.log.elastic.name }}
          mountPath: /data
        env:
        - name: "NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: {{ .Values.log.elastic.name }}
        emptyDir: {}
      initContainers:
      - image: alpine:3.6
        command: ["/sbin/sysctl", "-w", "vm.max_map_count=262144"]
        name: elasticsearch-logging-init
        securityContext:
          privileged: true
