apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.log.elastic.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.elastic.label }}
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: db
  selector:
    k8s-app: {{ .Values.log.elastic.label }}
