apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.log.filebeat.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.filebeat.label }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ .Values.log.filebeat.name }}
  labels:
    k8s-app: {{ .Values.log.filebeat.label }}
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.log.filebeat.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.log.filebeat.name }}
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ .Values.log.filebeat.name }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.log.filebeat.name }}-config
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.filebeat.label }}
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false
    output.logstash:
      hosts: ['logstash-service:5044']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.log.filebeat.name }}-prospectors
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.filebeat.label }}
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.log.filebeat.name }}
  namespace: kube-system
  labels:
    k8s-app: {{ .Values.log.filebeat.label }}
spec:
  selector:
    matchLabels:
        k8s-app: {{ .Values.log.filebeat.label }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.log.filebeat.label }}
  
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: {{ .Values.log.filebeat.name }}
        image: docker.elastic.co/beats/filebeat:6.8.4
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ .Values.log.filebeat.name }}-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: prospectors
        configMap:
          defaultMode: 0600
          name: {{ .Values.log.filebeat.name }}-prospectors
      - name: data
        emptyDir: {}
